CREATE TABLE customer_support_tickets_complete (
  ticket_id INTEGER PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  product TEXT NOT NULL,
  category TEXT NOT NULL,
  issue_description TEXT NOT NULL,
  resolution_notes TEXT NOT NULL,
  priority TEXT NOT NULL,
  status TEXT NOT NULL,
  channel TEXT NOT NULL,
  region TEXT NOT NULL,
  customer_age INTEGER NOT NULL,
  customer_gender TEXT NOT NULL,
  subscription_type TEXT NOT NULL,
  customer_tenure_months INTEGER NOT NULL,
  previous_tickets INTEGER NOT NULL,
  customer_satisfaction_score DOUBLE PRECISION NOT NULL,
  first_response_time_hours DOUBLE PRECISION NOT NULL,
  resolution_time_hours DOUBLE PRECISION NOT NULL,
  ticket_created_date DATE NOT NULL,
  ticket_resolved_date DATE NOT NULL,
  escalated BOOLEAN NOT NULL,
  sla_breached BOOLEAN NOT NULL,
  operating_system TEXT NOT NULL,
  browser TEXT,
  payment_method TEXT NOT NULL,
  language TEXT NOT NULL,
  preferred_contact_time TEXT NOT NULL,
  issue_complexity_score DOUBLE PRECISION NOT NULL,
  customer_segment TEXT NOT NULL
);

-- Real, operational tickets: most columns are unknown at import time and
-- get filled in later by the AI triage step or by an agent resolving the
-- ticket. sentiment/draft_response don't exist in customer_support_tickets_complete
-- at all — they're produced by this app, never imported from a CSV.
CREATE TABLE tickets (
  ticket_id INTEGER PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  issue_description TEXT NOT NULL,
  ticket_created_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'Open',
  escalated BOOLEAN NOT NULL DEFAULT false,
  sla_breached BOOLEAN NOT NULL DEFAULT false,
  product TEXT,
  category TEXT,
  resolution_notes TEXT,
  priority TEXT,
  channel TEXT,
  region TEXT,
  customer_age INTEGER,
  customer_gender TEXT,
  subscription_type TEXT,
  customer_tenure_months INTEGER,
  previous_tickets INTEGER,
  customer_satisfaction_score DOUBLE PRECISION,
  first_response_time_hours DOUBLE PRECISION,
  resolution_time_hours DOUBLE PRECISION,
  ticket_resolved_date DATE,
  operating_system TEXT,
  browser TEXT,
  payment_method TEXT,
  language TEXT,
  preferred_contact_time TEXT,
  issue_complexity_score DOUBLE PRECISION,
  customer_segment TEXT,
  sentiment TEXT,
  draft_response TEXT
);
